### ISSUE TITLE
starting docker container fails

### ISSUE THREAD

**Issue by jakabk** [zzzsochi/smtp-faker#3]
We tested it in two independent machine
(Debian Stretch, Docker version: 18.06; Arch linux, Docker version: 18.06)

Starting container:
```docker run --rm -it -p 8080:80 -p 8025:25 --name smtp-faker zzzsochi/smtp-faker```

We got error:

    ======== Runing SMTP server on 0.0.0.0:25 ========
    Traceback (most recent call last):
      File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/lib/python3.6/site-packages/smtp_faker/__main__.py", line 74, in <module>
        main()
      File "/usr/lib/python3.6/site-packages/smtp_faker/__main__.py", line 70, in main
        loop=loop)
    TypeError: run_app() got an unexpected keyword argument 'loop'

**Comment by zzzsochi** [comment]
Fixed.

```
 $ docker run --rm -it -p 8080:80 -p 8025:25 --name smtp-faker zzzsochi/smtp-faker
Unable to find image 'zzzsochi/smtp-faker:latest' locally
latest: Pulling from zzzsochi/smtp-faker
8e3ba11ec2a2: Already exists
76c23f0c8eee: Pull complete
fd5596fb5367: Pull complete
Digest: sha256:5fadb7f5deb825c4a17cc7328e5e5c1d48014a02132ead68333a9b424a8ff727
Status: Downloaded newer image for zzzsochi/smtp-faker:latest
======== Running SMTP server on 0.0.0.0:25 ========
======== Running on http://0.0.0.0:80 ========
(Press CTRL+C to quit)
```
